version: '3.8'

services:
  app-finance:
    build: .
    container_name: app-finance
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-finance-network
    # command: sh -c "composer install -n"
  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - 8888:80
    #   - 445:443
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-finance-network
  db_app_finance:
    container_name: db_app_finance
    image: mysql:5.7
    restart: always
    ports: 
      - '3309:3306'
    environment:
      - MYSQL_DATABASE=app_finance
      - MYSQL_USER=finance
      - MYSQL_PASSWORD=finance010203
      - MYSQL_ROOT_PASSWORD=root010203
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app-finance-network

networks:
  app-finance-network:
    driver: bridge