version: '3'

services:
  app-finance:
    build: .
    restart: always
    container_name: app-finance
    ports:
      - '7072:80'
    volumes:
      - .:/var/www
    networks:
      - default
    # command: bash -c "ln -sf ./public ./html"
    command: ["ln", "-s", "./public", "./html"]
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    ports: 
      - '3309:3306'
    environment:
      MYSQL_DATABASE: app_finance
      MYSQL_USER: finance
      MYSQL_PASSWORD: finance010203
      MYSQL_ROOT_PASSWORD: root010203
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - default
